export interface DataExchangeTable {
    table: string;
    sheet: string;
    columns: string[];
    columnLabels: Record<string, string>;
}

type DataExchangeTableDefinition = Omit<DataExchangeTable, 'columnLabels'> & {
    columnLabels?: Record<string, string>;
};

const commonColumnLabels: Record<string, string> = {
    id: 'ID',
    unified_pricing: '统一溢价开关',
    unified_rate: '统一溢价比例',
    rounding_type: '取整方式',
    cpu_rate: 'CPU 溢价比例',
    motherboard_rate: '主板溢价比例',
    ram_rate: '内存溢价比例',
    gpu_rate: '显卡溢价比例',
    storage_rate: '硬盘溢价比例',
    psu_rate: '电源溢价比例',
    case_rate: '机箱溢价比例',
    cooling_rate: '散热溢价比例',
    monitor_rate: '显示器溢价比例',
    created_at: '创建时间',
    updated_at: '更新时间',
    code: '编码',
    name: '名称',
    label: '显示名称',
    tag_color: '标签颜色',
    sort_order: '排序',
    is_active: '是否启用',
    category_id: '类目ID',
    rate: '溢价比例',
    contact: '联系方式',
    company_id: '物流公司ID',
    self_amount_cents: '我方承担金额(分)',
    occurred_at: '发生时间',
    related_type: '关联业务类型',
    related_id: '关联业务ID',
    settlement_target: '结算对象',
    payment_status: '付款状态',
    contact_name: '联系人',
    phone: '电话',
    address: '地址',
    note: '备注',
    category: '类目',
    barcode: '条形码',
    price_cents: '价格(分)',
    stock_quantity: '库存数量',
    selling_price_cents: '销售价(分)',
    is_use_premium: '是否使用溢价',
    supplier_id: '供应商ID',
    status: '状态',
    ordered_at: '下单时间',
    expected_inbound_at: '预计入库时间',
    shipping_fee_cents: '运费(分)',
    misc_fee_cents: '杂费(分)',
    purchase_order_id: '进货单ID',
    product_id: '产品ID',
    ordered_quantity: '订购数量',
    received_quantity: '已收数量',
    purchase_price_cents: '采购价(分)',
    amount_cents: '金额(分)',
    payment_account: '付款账户',
    paid_at: '付款时间',
    voided_at: '作废时间',
    void_reason: '作废原因',
    is_paid: '是否已付款',
    source_type: '来源类型',
    inbound_at: '入库时间',
    inbound_order_id: '入库单ID',
    quantity: '数量',
    purchase_order_item_id: '进货明细ID',
    serial_tracking_enabled: '是否启用序列号追踪',
    warranty_enabled: '是否启用保修',
    warranty_until: '保修截止时间',
    inbound_order_item_id: '入库明细ID',
    cost_price_cents: '成本价(分)',
    serial_number: '序列号',
    purchase_return_id: '采购退货ID',
    type: '类型',
    reason: '原因',
    goods_status: '货物状态',
    shipping_fee_bearer: '运费承担方',
    self_shipping_fee_cents: '我方运费(分)',
    merchant_shipping_fee_cents: '商家运费(分)',
    logistics_company_id: '物流公司ID',
    logistics_company: '物流公司',
    tracking_no: '物流单号',
    shipped_at: '发货时间',
    merchant_received_at: '商家收货时间',
    cancelled_at: '取消时间',
    cancel_reason: '取消原因',
    refund_account: '退款账户',
    refunded_at: '退款时间',
    description: '描述',
    total_price_cents: '总价(分)',
    package_id: '套餐ID',
    order_no: '订单号',
    customer_name: '客户姓名',
    customer_phone: '客户电话',
    original_amount_cents: '原始金额(分)',
    final_amount_cents: '最终金额(分)',
    discount_amount_cents: '优惠金额(分)',
    cost_amount_cents: '成本金额(分)',
    profit_amount_cents: '利润金额(分)',
    source: '来源',
    created_by_user_id: '创建人ID',
    created_by_username: '创建人账号',
    latest_adjustment_id: '最新改单ID',
    sold_at: '销售时间',
    order_id: '订单ID',
    product_name: '产品名称',
    product_category: '产品类目',
    sale_price_cents: '销售单价(分)',
    previous_adjustment_id: '上一次改单ID',
    previous_adjusted_amount_cents: '上次调整后金额(分)',
    adjusted_amount_cents: '调整金额(分)',
    previous_final_amount_cents: '上次最终金额(分)',
    adjustment_note: '改单备注',
    adjustment_id: '改单ID',
    source_order_item_id: '来源订单明细ID',
    order_item_id: '订单明细ID',
    adjustment_item_id: '改单明细ID',
    inventory_item_id: '库存单件ID',
    cost_date: '成本日期',
};

const createColumnLabels = (
    table: string,
    columns: string[],
    overrides: Record<string, string> = {}
) => {
    const labels = columns.reduce<Record<string, string>>((acc, column) => {
        const label = overrides[column] || commonColumnLabels[column];
        if (!label) {
            throw new Error(`Missing data exchange column label: ${table}.${column}`);
        }

        acc[column] = label;
        return acc;
    }, {});

    return labels;
};

const createDataExchangeTable = (definition: DataExchangeTableDefinition): DataExchangeTable => ({
    ...definition,
    columnLabels: createColumnLabels(definition.table, definition.columns, definition.columnLabels),
});

const dataExchangeTableDefinitions: DataExchangeTableDefinition[] = [
    {
        table: 'pricing_config',
        sheet: '溢价配置',
        columns: [
            'id',
            'unified_pricing',
            'unified_rate',
            'rounding_type',
            'cpu_rate',
            'motherboard_rate',
            'ram_rate',
            'gpu_rate',
            'storage_rate',
            'psu_rate',
            'case_rate',
            'cooling_rate',
            'monitor_rate',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'product_categories',
        sheet: '商品类目',
        columns: [
            'id',
            'code',
            'name',
            'label',
            'tag_color',
            'sort_order',
            'is_active',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'category_pricing_rates',
        sheet: '类目溢价',
        columns: ['id', 'category_id', 'rate', 'created_at', 'updated_at'],
    },
    {
        table: 'suppliers',
        sheet: '进货商家',
        columns: [
            'id',
            'name',
            'contact_name',
            'phone',
            'address',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'logistics_companies',
        sheet: '物流公司',
        columns: ['id', 'name', 'contact', 'note', 'status', 'created_at', 'updated_at'],
    },
    {
        table: 'logistics_records',
        sheet: '物流记录',
        columns: [
            'id',
            'type',
            'company_id',
            'tracking_no',
            'shipping_fee_cents',
            'self_amount_cents',
            'occurred_at',
            'related_type',
            'related_id',
            'shipping_fee_bearer',
            'settlement_target',
            'payment_status',
            'paid_at',
            'payment_account',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'products',
        sheet: '产品型号',
        columns: [
            'id',
            'category',
            'category_id',
            'name',
            'barcode',
            'price_cents',
            'stock_quantity',
            'selling_price_cents',
            'is_use_premium',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_orders',
        sheet: '进货单',
        columns: [
            'id',
            'supplier_id',
            'status',
            'ordered_at',
            'expected_inbound_at',
            'shipping_fee_cents',
            'misc_fee_cents',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_order_items',
        sheet: '进货明细',
        columns: [
            'id',
            'purchase_order_id',
            'product_id',
            'ordered_quantity',
            'received_quantity',
            'purchase_price_cents',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_payments',
        sheet: '进货付款记录',
        columns: [
            'id',
            'purchase_order_id',
            'amount_cents',
            'payment_account',
            'paid_at',
            'status',
            'voided_at',
            'void_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_orders',
        sheet: '入库单',
        columns: [
            'id',
            'supplier_id',
            'shipping_fee_cents',
            'misc_fee_cents',
            'is_paid',
            'source_type',
            'purchase_order_id',
            'status',
            'inbound_at',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_order_items',
        sheet: '入库明细',
        columns: [
            'id',
            'inbound_order_id',
            'product_id',
            'quantity',
            'purchase_price_cents',
            'purchase_order_item_id',
            'serial_tracking_enabled',
            'warranty_enabled',
            'warranty_until',
            'note',
            'created_at',
        ],
    },
    {
        table: 'inventory_items',
        sheet: '库存单件',
        columns: [
            'id',
            'product_id',
            'supplier_id',
            'inbound_order_id',
            'inbound_order_item_id',
            'cost_price_cents',
            'serial_number',
            'warranty_enabled',
            'warranty_until',
            'inbound_at',
            'status',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_returns',
        sheet: '采购退货记录',
        columns: [
            'id',
            'purchase_order_id',
            'inbound_order_id',
            'type',
            'reason',
            'status',
            'goods_status',
            'shipping_fee_cents',
            'shipping_fee_bearer',
            'self_shipping_fee_cents',
            'merchant_shipping_fee_cents',
            'logistics_company_id',
            'logistics_company',
            'tracking_no',
            'shipped_at',
            'merchant_received_at',
            'cancelled_at',
            'cancel_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_return_items',
        sheet: '采购退货明细',
        columns: [
            'id',
            'purchase_return_id',
            'purchase_order_item_id',
            'inbound_order_item_id',
            'inventory_item_id',
            'product_id',
            'purchase_price_cents',
            'created_at',
        ],
    },
    {
        table: 'purchase_refunds',
        sheet: '供应商退款记录',
        columns: [
            'id',
            'purchase_order_id',
            'purchase_return_id',
            'amount_cents',
            'refund_account',
            'refunded_at',
            'status',
            'voided_at',
            'void_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'packages',
        sheet: '套餐',
        columns: ['id', 'name', 'description', 'total_price_cents', 'created_at', 'updated_at'],
    },
    {
        table: 'package_items',
        sheet: '套餐明细',
        columns: ['id', 'package_id', 'product_id', 'quantity', 'created_at'],
    },
    {
        table: 'sales_orders',
        sheet: '销售订单',
        columns: [
            'id',
            'order_no',
            'customer_name',
            'customer_phone',
            'original_amount_cents',
            'final_amount_cents',
            'discount_amount_cents',
            'cost_amount_cents',
            'profit_amount_cents',
            'status',
            'is_paid',
            'source',
            'created_by_user_id',
            'created_by_username',
            'latest_adjustment_id',
            'note',
            'sold_at',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'sales_order_items',
        sheet: '销售订单明细',
        columns: [
            'id',
            'order_id',
            'product_id',
            'product_name',
            'product_category',
            'quantity',
            'cost_price_cents',
            'sale_price_cents',
            'created_at',
        ],
    },
    {
        table: 'sales_order_adjustments',
        sheet: '销售订单改单记录',
        columns: [
            'id',
            'order_id',
            'previous_adjustment_id',
            'original_amount_cents',
            'previous_adjusted_amount_cents',
            'adjusted_amount_cents',
            'previous_final_amount_cents',
            'final_amount_cents',
            'adjustment_note',
            'created_by_user_id',
            'created_by_username',
            'created_at',
        ],
    },
    {
        table: 'sales_order_adjustment_items',
        sheet: '销售订单改单明细',
        columns: [
            'id',
            'adjustment_id',
            'source_order_item_id',
            'product_id',
            'product_name',
            'product_category',
            'quantity',
            'sale_price_cents',
            'created_at',
        ],
    },
    {
        table: 'order_inventory_items',
        sheet: '订单库存绑定',
        columns: [
            'id',
            'order_id',
            'order_item_id',
            'adjustment_item_id',
            'inventory_item_id',
            'cost_price_cents',
            'created_at',
        ],
    },
    {
        table: 'operating_costs',
        sheet: '经营成本',
        columns: [
            'id',
            'type',
            'name',
            'amount_cents',
            'cost_date',
            'note',
            'created_at',
            'updated_at',
        ],
    },
];

export const dataExchangeTables: DataExchangeTable[] =
    dataExchangeTableDefinitions.map(createDataExchangeTable);

export const dataExchangeTableMap = new Map(
    dataExchangeTables.map((table) => [table.table, table])
);
