export interface DataExchangeTable {
    table: string;
    sheet: string;
    columns: string[];
}

export const dataExchangeTables: DataExchangeTable[] = [
    {
        table: 'pricing_config',
        sheet: '溢价配置',
        columns: [
            'id',
            'unified_pricing',
            'unified_rate',
            'rounding_type',
            'cpu_rate',
            'motherboard_rate',
            'ram_rate',
            'gpu_rate',
            'storage_rate',
            'psu_rate',
            'case_rate',
            'cooling_rate',
            'monitor_rate',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'product_categories',
        sheet: '商品类目',
        columns: [
            'id',
            'code',
            'name',
            'label',
            'tag_color',
            'sort_order',
            'is_active',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'category_pricing_rates',
        sheet: '类目溢价',
        columns: ['id', 'category_id', 'rate', 'created_at', 'updated_at'],
    },
    {
        table: 'suppliers',
        sheet: '进货商家',
        columns: [
            'id',
            'name',
            'contact_name',
            'phone',
            'address',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'products',
        sheet: '产品型号',
        columns: [
            'id',
            'category',
            'category_id',
            'name',
            'barcode',
            'price_cents',
            'stock_quantity',
            'selling_price_cents',
            'is_use_premium',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_orders',
        sheet: '进货单',
        columns: [
            'id',
            'supplier_id',
            'status',
            'ordered_at',
            'expected_inbound_at',
            'shipping_fee_cents',
            'misc_fee_cents',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_order_items',
        sheet: '进货明细',
        columns: [
            'id',
            'purchase_order_id',
            'product_id',
            'ordered_quantity',
            'received_quantity',
            'purchase_price_cents',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_payments',
        sheet: '进货付款记录',
        columns: [
            'id',
            'purchase_order_id',
            'amount_cents',
            'payment_account',
            'paid_at',
            'status',
            'voided_at',
            'void_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_orders',
        sheet: '入库单',
        columns: [
            'id',
            'supplier_id',
            'shipping_fee_cents',
            'misc_fee_cents',
            'is_paid',
            'source_type',
            'purchase_order_id',
            'status',
            'inbound_at',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_order_items',
        sheet: '入库明细',
        columns: [
            'id',
            'inbound_order_id',
            'product_id',
            'quantity',
            'purchase_price_cents',
            'purchase_order_item_id',
            'serial_tracking_enabled',
            'warranty_enabled',
            'warranty_until',
            'note',
            'created_at',
        ],
    },
    {
        table: 'inventory_items',
        sheet: '库存单件',
        columns: [
            'id',
            'product_id',
            'supplier_id',
            'inbound_order_id',
            'inbound_order_item_id',
            'cost_price_cents',
            'serial_number',
            'warranty_enabled',
            'warranty_until',
            'inbound_at',
            'status',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_returns',
        sheet: '采购退货记录',
        columns: [
            'id',
            'purchase_order_id',
            'inbound_order_id',
            'type',
            'reason',
            'status',
            'goods_status',
            'shipping_fee_cents',
            'shipping_fee_bearer',
            'self_shipping_fee_cents',
            'merchant_shipping_fee_cents',
            'logistics_company',
            'tracking_no',
            'shipped_at',
            'merchant_received_at',
            'cancelled_at',
            'cancel_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'purchase_return_items',
        sheet: '采购退货明细',
        columns: [
            'id',
            'purchase_return_id',
            'purchase_order_item_id',
            'inbound_order_item_id',
            'inventory_item_id',
            'product_id',
            'purchase_price_cents',
            'created_at',
        ],
    },
    {
        table: 'purchase_refunds',
        sheet: '供应商退款记录',
        columns: [
            'id',
            'purchase_order_id',
            'purchase_return_id',
            'amount_cents',
            'refund_account',
            'refunded_at',
            'status',
            'voided_at',
            'void_reason',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'packages',
        sheet: '套餐',
        columns: ['id', 'name', 'description', 'total_price_cents', 'created_at', 'updated_at'],
    },
    {
        table: 'package_items',
        sheet: '套餐明细',
        columns: ['id', 'package_id', 'product_id', 'quantity', 'created_at'],
    },
    {
        table: 'sales_orders',
        sheet: '销售订单',
        columns: [
            'id',
            'order_no',
            'customer_name',
            'customer_phone',
            'original_amount_cents',
            'final_amount_cents',
            'discount_amount_cents',
            'cost_amount_cents',
            'profit_amount_cents',
            'status',
            'is_paid',
            'source',
            'created_by_user_id',
            'created_by_username',
            'latest_adjustment_id',
            'note',
            'sold_at',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'sales_order_items',
        sheet: '销售订单明细',
        columns: [
            'id',
            'order_id',
            'product_id',
            'product_name',
            'product_category',
            'quantity',
            'cost_price_cents',
            'sale_price_cents',
            'created_at',
        ],
    },
    {
        table: 'sales_order_adjustments',
        sheet: '销售订单改单记录',
        columns: [
            'id',
            'order_id',
            'previous_adjustment_id',
            'original_amount_cents',
            'previous_adjusted_amount_cents',
            'adjusted_amount_cents',
            'previous_final_amount_cents',
            'final_amount_cents',
            'adjustment_note',
            'created_by_user_id',
            'created_by_username',
            'created_at',
        ],
    },
    {
        table: 'sales_order_adjustment_items',
        sheet: '销售订单改单明细',
        columns: [
            'id',
            'adjustment_id',
            'source_order_item_id',
            'product_id',
            'product_name',
            'product_category',
            'quantity',
            'sale_price_cents',
            'created_at',
        ],
    },
    {
        table: 'order_inventory_items',
        sheet: '订单库存绑定',
        columns: [
            'id',
            'order_id',
            'order_item_id',
            'adjustment_item_id',
            'inventory_item_id',
            'cost_price_cents',
            'created_at',
        ],
    },
    {
        table: 'operating_costs',
        sheet: '经营成本',
        columns: [
            'id',
            'type',
            'name',
            'amount_cents',
            'cost_date',
            'note',
            'created_at',
            'updated_at',
        ],
    },
];

export const dataExchangeDeleteOrder = [
    'order_inventory_items',
    'sales_order_adjustment_items',
    'sales_order_adjustments',
    'sales_order_items',
    'sales_orders',
    'purchase_refunds',
    'purchase_return_items',
    'purchase_returns',
    'inventory_items',
    'inbound_order_items',
    'inbound_orders',
    'purchase_payments',
    'purchase_order_items',
    'purchase_orders',
    'package_items',
    'packages',
    'operating_costs',
    'products',
    'suppliers',
    'category_pricing_rates',
    'product_categories',
    'pricing_config',
];
