export interface DataExchangeTable {
    table: string;
    sheet: string;
    columns: string[];
}

export const dataExchangeTables: DataExchangeTable[] = [
    {
        table: 'pricing_config',
        sheet: '溢价配置',
        columns: [
            'id',
            'unified_pricing',
            'unified_rate',
            'rounding_type',
            'cpu_rate',
            'motherboard_rate',
            'ram_rate',
            'gpu_rate',
            'storage_rate',
            'psu_rate',
            'case_rate',
            'cooling_rate',
            'monitor_rate',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'suppliers',
        sheet: '进货商家',
        columns: [
            'id',
            'name',
            'contact_name',
            'phone',
            'address',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'products',
        sheet: '产品型号',
        columns: [
            'id',
            'category',
            'name',
            'price_cents',
            'stock_quantity',
            'selling_price_cents',
            'is_use_premium',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_orders',
        sheet: '入库单',
        columns: [
            'id',
            'supplier_id',
            'shipping_fee_cents',
            'misc_fee_cents',
            'is_paid',
            'inbound_at',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'inbound_order_items',
        sheet: '入库明细',
        columns: [
            'id',
            'inbound_order_id',
            'product_id',
            'quantity',
            'purchase_price_cents',
            'warranty_enabled',
            'warranty_until',
            'note',
            'created_at',
        ],
    },
    {
        table: 'inventory_items',
        sheet: '库存单件',
        columns: [
            'id',
            'product_id',
            'supplier_id',
            'inbound_order_id',
            'inbound_order_item_id',
            'cost_price_cents',
            'serial_number',
            'warranty_enabled',
            'warranty_until',
            'inbound_at',
            'status',
            'note',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'packages',
        sheet: '套餐',
        columns: ['id', 'name', 'description', 'total_price_cents', 'created_at', 'updated_at'],
    },
    {
        table: 'package_items',
        sheet: '套餐明细',
        columns: ['id', 'package_id', 'product_id', 'quantity', 'created_at'],
    },
    {
        table: 'sales_orders',
        sheet: '销售订单',
        columns: [
            'id',
            'order_no',
            'customer_name',
            'customer_phone',
            'original_amount_cents',
            'final_amount_cents',
            'discount_amount_cents',
            'cost_amount_cents',
            'profit_amount_cents',
            'status',
            'is_paid',
            'source',
            'note',
            'sold_at',
            'created_at',
            'updated_at',
        ],
    },
    {
        table: 'sales_order_items',
        sheet: '销售订单明细',
        columns: [
            'id',
            'order_id',
            'product_id',
            'product_name',
            'product_category',
            'quantity',
            'cost_price_cents',
            'sale_price_cents',
            'created_at',
        ],
    },
    {
        table: 'order_inventory_items',
        sheet: '订单库存绑定',
        columns: [
            'id',
            'order_id',
            'order_item_id',
            'inventory_item_id',
            'cost_price_cents',
            'created_at',
        ],
    },
    {
        table: 'operating_costs',
        sheet: '经营成本',
        columns: [
            'id',
            'type',
            'name',
            'amount_cents',
            'cost_date',
            'note',
            'created_at',
            'updated_at',
        ],
    },
];

export const dataExchangeDeleteOrder = [
    'order_inventory_items',
    'sales_order_items',
    'sales_orders',
    'inventory_items',
    'inbound_order_items',
    'inbound_orders',
    'package_items',
    'packages',
    'operating_costs',
    'products',
    'suppliers',
    'pricing_config',
];
