services:
    computer:
        build:
            context: .
        image: computer-parts-pricing:latest
        container_name: computer-parts-pricing
        restart: unless-stopped
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: production
            SQLITE_DB_PATH: /app/data/computer.db
        volumes:
            - computer_data:/app/data

volumes:
    computer_data:
