import { AntdGlobalRegistry } from '@/lib/AntdGlobal';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App } from 'antd';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';
import { ThemeProvider } from '@/app/_components/ThemeProvider';
import { cookies } from 'next/headers';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const theme = cookieStore.get('theme')?.value as 'light' | 'dark' | 'system' | undefined;
    const isDark = theme === 'dark';

    return (
        <html lang="en" className={isDark ? 'dark' : ''} suppressHydrationWarning>
            <head>
                <style
                    dangerouslySetInnerHTML={{
                        __html: `
                            .dark { background-color: #141414 !important; color: #ededed; }
                            .dark body { background-color: #141414 !important; }
                        `,
                    }}
                />
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            (function() {
                                try {
                                    var localTheme = localStorage.getItem('theme');
                                    var supportDarkMode = window.matchMedia('(prefers-color-scheme: dark)').matches === true;
                                    if (!localTheme || localTheme === 'system') {
                                        if (supportDarkMode) {
                                            document.documentElement.classList.add('dark');
                                        }
                                    } else if (localTheme === 'dark') {
                                        document.documentElement.classList.add('dark');
                                    }
                                } catch (e) {}
                            })();
                        `,
                    }}
                />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <NextTopLoader
                    color="#4f46e5"
                    initialPosition={0.08}
                    crawlSpeed={200}
                    height={3}
                    crawl={true}
                    showSpinner={false}
                    easing="ease"
                    speed={200}
                    shadow="0 0 10px #4f46e5,0 0 5px #4f46e5"
                />
                <AntdRegistry>
                    <ThemeProvider initialTheme={theme}>
                        <App>
                            <AntdGlobalRegistry />
                            {children}
                        </App>
                    </ThemeProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
