import { Package, Product } from './types';

/**
 * 演示模式产品数据
 */
export const MOCK_PRODUCTS: Product[] = [
    // CPU
    {
        id: 1,
        name: 'Intel Core i9-13900K',
        price: 589.99,
        category: 'cpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 2,
        name: 'AMD Ryzen 9 7950X',
        price: 549.99,
        category: 'cpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 3,
        name: 'Intel Core i7-13700K',
        price: 419.99,
        category: 'cpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // Motherboard
    {
        id: 4,
        name: 'ASUS ROG Maximus Z790 Hero',
        price: 599.99,
        category: 'motherboard',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 5,
        name: 'MSI MEG X670E ACE',
        price: 499.99,
        category: 'motherboard',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 6,
        name: 'Gigabyte B650 AORUS Elite AX',
        price: 229.99,
        category: 'motherboard',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // RAM
    {
        id: 7,
        name: 'Corsair Dominator Platinum RGB 32GB DDR5 6000MHz',
        price: 249.99,
        category: 'ram',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 8,
        name: 'G.Skill Trident Z5 RGB 32GB DDR5 6000MHz',
        price: 219.99,
        category: 'ram',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 9,
        name: 'Kingston Fury Beast 32GB DDR5 5200MHz',
        price: 149.99,
        category: 'ram',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // GPU
    {
        id: 10,
        name: 'NVIDIA GeForce RTX 4090 Founders Edition',
        price: 1599.99,
        category: 'gpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 11,
        name: 'AMD Radeon RX 7900 XTX',
        price: 999.99,
        category: 'gpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 12,
        name: 'NVIDIA GeForce RTX 4080',
        price: 1199.99,
        category: 'gpu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // Storage
    {
        id: 13,
        name: 'Samsung 990 Pro 2TB NVMe SSD',
        price: 249.99,
        category: 'storage',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 14,
        name: 'WD Black SN850X 2TB NVMe SSD',
        price: 229.99,
        category: 'storage',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 15,
        name: 'Crucial P5 Plus 2TB NVMe SSD',
        price: 199.99,
        category: 'storage',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // PSU
    {
        id: 16,
        name: 'Corsair HX1200 Platinum 1200W',
        price: 299.99,
        category: 'psu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 17,
        name: 'Seasonic PRIME TX-1000 1000W',
        price: 279.99,
        category: 'psu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 18,
        name: 'EVGA SuperNOVA 850 G6 850W',
        price: 159.99,
        category: 'psu',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // Case
    {
        id: 19,
        name: 'Lian Li PC-O11 Dynamic',
        price: 149.99,
        category: 'case',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 20,
        name: 'Fractal Design Torrent',
        price: 199.99,
        category: 'case',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 21,
        name: 'NZXT H7 Flow',
        price: 129.99,
        category: 'case',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    // Cooling
    {
        id: 22,
        name: 'NZXT Kraken Z73 RGB 360mm',
        price: 279.99,
        category: 'cooling',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 23,
        name: 'Corsair iCUE H150i ELITE LCD',
        price: 249.99,
        category: 'cooling',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
    {
        id: 24,
        name: 'Noctua NH-D15 chromax.black',
        price: 109.99,
        category: 'cooling',
        selling_price: null,
        is_use_premium: true,
        updated_at: '2024-01-15T08:00:00Z',
    },
];

/**
 * 演示模式套餐数据
 */
export const MOCK_PACKAGES: Package[] = [
    {
        id: 1,
        name: '高性能游戏主机套餐',
        description: '适合3A大作和高帧率游戏的旗舰级配置,包含最新一代顶级CPU、显卡和主板,性能强劲',
        total_price: 4569.91,
        created_at: '2024-01-15T08:00:00Z',
        updated_at: '2024-01-15T08:00:00Z',
        items: [
            {
                product_id: 1,
                quantity: 1,
                product_name: 'Intel Core i9-13900K',
                product_price: 589.99,
                product_category: 'cpu',
            },
            {
                product_id: 4,
                quantity: 1,
                product_name: 'ASUS ROG Maximus Z790 Hero',
                product_price: 599.99,
                product_category: 'motherboard',
            },
            {
                product_id: 7,
                quantity: 2,
                product_name: 'Corsair Dominator Platinum RGB 32GB DDR5 6000MHz',
                product_price: 249.99,
                product_category: 'ram',
            },
            {
                product_id: 10,
                quantity: 1,
                product_name: 'NVIDIA GeForce RTX 4090 Founders Edition',
                product_price: 1599.99,
                product_category: 'gpu',
            },
            {
                product_id: 13,
                quantity: 2,
                product_name: 'Samsung 990 Pro 2TB NVMe SSD',
                product_price: 249.99,
                product_category: 'storage',
            },
            {
                product_id: 16,
                quantity: 1,
                product_name: 'Corsair HX1200 Platinum 1200W',
                product_price: 299.99,
                product_category: 'psu',
            },
            {
                product_id: 20,
                quantity: 1,
                product_name: 'Fractal Design Torrent',
                product_price: 199.99,
                product_category: 'case',
            },
            {
                product_id: 22,
                quantity: 1,
                product_name: 'NZXT Kraken Z73 RGB 360mm',
                product_price: 279.99,
                product_category: 'cooling',
            },
        ],
    },
    {
        id: 2,
        name: '性价比办公套餐',
        description: '满足日常办公和轻度娱乐需求的经济型配置',
        total_price: 1659.93,
        created_at: '2024-01-16T10:30:00Z',
        updated_at: '2024-01-16T10:30:00Z',
        items: [
            {
                product_id: 3,
                quantity: 1,
                product_name: 'Intel Core i7-13700K',
                product_price: 419.99,
                product_category: 'cpu',
            },
            {
                product_id: 6,
                quantity: 1,
                product_name: 'Gigabyte B650 AORUS Elite AX',
                product_price: 229.99,
                product_category: 'motherboard',
            },
            {
                product_id: 9,
                quantity: 1,
                product_name: 'Kingston Fury Beast 32GB DDR5 5200MHz',
                product_price: 149.99,
                product_category: 'ram',
            },
            {
                product_id: 11,
                quantity: 1,
                product_name: 'AMD Radeon RX 7900 XTX',
                product_price: 999.99,
                product_category: 'gpu',
            },
            {
                product_id: 15,
                quantity: 1,
                product_name: 'Crucial P5 Plus 2TB NVMe SSD',
                product_price: 199.99,
                product_category: 'storage',
            },
            {
                product_id: 18,
                quantity: 1,
                product_name: 'EVGA SuperNOVA 850 G6 850W',
                product_price: 159.99,
                product_category: 'psu',
            },
            {
                product_id: 21,
                quantity: 1,
                product_name: 'NZXT H7 Flow',
                product_price: 129.99,
                product_category: 'case',
            },
            {
                product_id: 24,
                quantity: 1,
                product_name: 'Noctua NH-D15 chromax.black',
                product_price: 109.99,
                product_category: 'cooling',
            },
        ],
    },
];
